export const mockJobs = [
  {
    id: "job-1",
    title: "Senior Frontend Developer",
    companyId: "company-1",
    location: "San Francisco, CA",
    type: "Full-time",
    experience: "Senior Level",
    salary: {
      min: 120000,
      max: 160000,
    },
    tags: ["React", "TypeScript", "Next.js", "Tailwind CSS"],
    postedAt: "2 days ago",
    description:
      "We are looking for a Senior Frontend Developer to join our team. You will be responsible for building user interfaces for our web applications. The ideal candidate has experience with React, TypeScript, and modern frontend frameworks.",
    requirements: [
      "5+ years of experience in frontend development",
      "Strong proficiency in JavaScript, TypeScript, and React",
      "Experience with Next.js and server-side rendering",
      "Knowledge of modern CSS frameworks like Tailwind CSS",
      "Understanding of web accessibility standards",
      "Experience with state management libraries like Redux or Zustand",
    ],
    responsibilities: [
      "Develop and maintain frontend applications using React and TypeScript",
      "Collaborate with designers to implement user interfaces",
      "Write clean, maintainable, and efficient code",
      "Optimize applications for maximum speed and scalability",
      "Participate in code reviews and mentor junior developers",
    ],
  },
  {
    id: "job-2",
    title: "Backend Engineer",
    companyId: "company-2",
    location: "Remote",
    type: "Full-time",
    experience: "Mid Level",
    salary: {
      min: 100000,
      max: 130000,
    },
    tags: ["Node.js", "Express", "MongoDB", "AWS"],
    postedAt: "1 week ago",
    description:
      "We're seeking a Backend Engineer to help build and scale our API services. The ideal candidate has experience with Node.js, Express, and database technologies.",
    requirements: [
      "3+ years of experience in backend development",
      "Strong proficiency in Node.js and Express",
      "Experience with MongoDB or other NoSQL databases",
      "Knowledge of RESTful API design principles",
      "Familiarity with AWS services",
      "Understanding of authentication and authorization mechanisms",
    ],
    responsibilities: [
      "Design and implement scalable API services",
      "Optimize database queries and performance",
      "Implement security best practices",
      "Write unit and integration tests",
      "Collaborate with frontend developers to integrate APIs",
    ],
  },
  {
    id: "job-3",
    title: "Full Stack Developer",
    companyId: "company-3",
    location: "New York, NY",
    type: "Full-time",
    experience: "Mid Level",
    salary: {
      min: 110000,
      max: 140000,
    },
    tags: ["React", "Node.js", "PostgreSQL", "Docker"],
    postedAt: "3 days ago",
    description:
      "We are looking for a Full Stack Developer to join our growing team. You will be responsible for developing and maintaining web applications from the database to the user interface.",
    requirements: [
      "3+ years of experience in full stack development",
      "Strong proficiency in JavaScript/TypeScript",
      "Experience with React and Node.js",
      "Knowledge of SQL databases, particularly PostgreSQL",
      "Familiarity with containerization using Docker",
      "Understanding of CI/CD pipelines",
    ],
    responsibilities: [
      "Develop and maintain full stack web applications",
      "Write clean, maintainable code for both frontend and backend",
      "Design and implement database schemas",
      "Optimize applications for performance and scalability",
      "Collaborate with cross-functional teams",
    ],
  },
  {
    id: "job-4",
    title: "DevOps Engineer",
    companyId: "company-4",
    location: "Seattle, WA",
    type: "Full-time",
    experience: "Senior Level",
    salary: {
      min: 130000,
      max: 170000,
    },
    tags: ["AWS", "Kubernetes", "Terraform", "CI/CD"],
    postedAt: "5 days ago",
    description:
      "We are seeking an experienced DevOps Engineer to help us build and maintain our cloud infrastructure. The ideal candidate has strong experience with AWS, Kubernetes, and infrastructure as code.",
    requirements: [
      "5+ years of experience in DevOps or SRE roles",
      "Strong proficiency with AWS services",
      "Experience with Kubernetes and container orchestration",
      "Knowledge of infrastructure as code using Terraform or CloudFormation",
      "Experience with CI/CD pipelines",
      "Understanding of monitoring and logging solutions",
    ],
    responsibilities: [
      "Design and implement cloud infrastructure",
      "Automate deployment processes",
      "Manage and optimize Kubernetes clusters",
      "Implement monitoring and alerting solutions",
      "Collaborate with development teams to improve deployment workflows",
    ],
  },
  {
    id: "job-5",
    title: "UI/UX Designer",
    companyId: "company-5",
    location: "Remote",
    type: "Full-time",
    experience: "Mid Level",
    salary: {
      min: 90000,
      max: 120000,
    },
    tags: ["Figma", "UI Design", "User Research", "Prototyping"],
    postedAt: "1 week ago",
    description:
      "We're looking for a talented UI/UX Designer to create beautiful, intuitive interfaces for our products. The ideal candidate has a strong portfolio demonstrating their design skills and user-centered approach.",
    requirements: [
      "3+ years of experience in UI/UX design",
      "Proficiency with design tools like Figma or Sketch",
      "Experience conducting user research and usability testing",
      "Strong understanding of design principles and accessibility",
      "Ability to create wireframes, prototypes, and high-fidelity designs",
      "Knowledge of design systems",
    ],
    responsibilities: [
      "Design intuitive and engaging user interfaces",
      "Create wireframes, prototypes, and high-fidelity designs",
      "Conduct user research and usability testing",
      "Collaborate with product managers and developers",
      "Maintain and evolve our design system",
    ],
  },
  {
    id: "job-6",
    title: "Product Manager",
    companyId: "company-1",
    location: "Austin, TX",
    type: "Full-time",
    experience: "Senior Level",
    salary: {
      min: 120000,
      max: 160000,
    },
    tags: ["Product Strategy", "Agile", "User Research", "Roadmapping"],
    postedAt: "2 weeks ago",
    description:
      "We are seeking an experienced Product Manager to lead our product development efforts. The ideal candidate has a track record of shipping successful products and working with cross-functional teams.",
    requirements: [
      "5+ years of experience in product management",
      "Experience leading cross-functional teams",
      "Strong understanding of agile methodologies",
      "Excellent communication and stakeholder management skills",
      "Data-driven approach to decision making",
      "Technical background preferred",
    ],
    responsibilities: [
      "Define product vision and strategy",
      "Create and maintain product roadmaps",
      "Work with engineering, design, and marketing teams",
      "Gather and prioritize product requirements",
      "Analyze market trends and competition",
    ],
  },
  {
    id: "job-7",
    title: "Data Scientist",
    companyId: "company-3",
    location: "Boston, MA",
    type: "Full-time",
    experience: "Mid Level",
    salary: {
      min: 110000,
      max: 150000,
    },
    tags: ["Python", "Machine Learning", "SQL", "Data Analysis"],
    postedAt: "3 days ago",
    description:
      "We're looking for a Data Scientist to help us extract insights from our data. The ideal candidate has strong analytical skills and experience with machine learning techniques.",
    requirements: [
      "3+ years of experience in data science or related field",
      "Strong proficiency in Python and data analysis libraries",
      "Experience with machine learning frameworks like TensorFlow or PyTorch",
      "Knowledge of SQL and database concepts",
      "Understanding of statistical analysis",
      "Experience with data visualization tools",
    ],
    responsibilities: [
      "Analyze complex datasets to extract insights",
      "Build and deploy machine learning models",
      "Create data visualizations and reports",
      "Collaborate with product and engineering teams",
      "Improve data collection procedures",
    ],
  },
  {
    id: "job-8",
    title: "Mobile Developer (iOS)",
    companyId: "company-2",
    location: "Remote",
    type: "Full-time",
    experience: "Mid Level",
    salary: {
      min: 100000,
      max: 140000,
    },
    tags: ["Swift", "iOS", "UIKit", "SwiftUI"],
    postedAt: "1 week ago",
    description:
      "We are seeking a talented iOS Developer to join our mobile team. You will be responsible for developing and maintaining our iOS applications.",
    requirements: [
      "3+ years of experience in iOS development",
      "Strong proficiency in Swift",
      "Experience with UIKit and SwiftUI",
      "Knowledge of iOS design patterns",
      "Understanding of RESTful APIs",
      "Experience with version control systems",
    ],
    responsibilities: [
      "Develop and maintain iOS applications",
      "Write clean, maintainable code",
      "Collaborate with designers and backend developers",
      "Troubleshoot and fix bugs",
      "Stay up-to-date with Apple's design principles and guidelines",
    ],
  },
]

export const mockCompanies = [
  {
    id: "company-1",
    name: "TechNova",
    logo: "/placeholder.svg?height=40&width=40",
    description:
      "TechNova is a leading technology company specializing in innovative software solutions for businesses of all sizes. We are dedicated to creating cutting-edge products that help our clients succeed in the digital age.",
    industry: "Software Development",
    size: "501-1000 employees",
    founded: 2010,
    website: "https://technova.example.com",
  },
  {
    id: "company-2",
    name: "DataFlow Systems",
    logo: "/placeholder.svg?height=40&width=40",
    description:
      "DataFlow Systems is a data analytics company that helps businesses make better decisions through advanced data processing and visualization tools. We transform complex data into actionable insights.",
    industry: "Data Analytics",
    size: "201-500 employees",
    founded: 2015,
    website: "https://dataflow.example.com",
  },
  {
    id: "company-3",
    name: "CloudScale",
    logo: "/placeholder.svg?height=40&width=40",
    description:
      "CloudScale is a cloud infrastructure company providing scalable solutions for modern applications. We help businesses build, deploy, and manage their applications in the cloud with ease.",
    industry: "Cloud Computing",
    size: "501-1000 employees",
    founded: 2012,
    website: "https://cloudscale.example.com",
  },
  {
    id: "company-4",
    name: "SecureNet",
    logo: "/placeholder.svg?height=40&width=40",
    description:
      "SecureNet is a cybersecurity company dedicated to protecting businesses from digital threats. We provide comprehensive security solutions to safeguard sensitive data and systems.",
    industry: "Cybersecurity",
    size: "101-200 employees",
    founded: 2014,
    website: "https://securenet.example.com",
  },
  {
    id: "company-5",
    name: "DesignHub",
    logo: "/placeholder.svg?height=40&width=40",
    description:
      "DesignHub is a creative agency specializing in user experience and interface design. We create beautiful, intuitive designs that enhance user engagement and satisfaction.",
    industry: "Design & Creative",
    size: "51-100 employees",
    founded: 2016,
    website: "https://designhub.example.com",
  },
]

export const mockCompanyJobs = [
  {
    id: "job-1",
    title: "Senior Frontend Developer",
    location: "San Francisco, CA",
    status: "Active",
    applications: 24,
    postedAt: "May 15, 2023",
  },
  {
    id: "job-6",
    title: "Product Manager",
    location: "Austin, TX",
    status: "Active",
    applications: 18,
    postedAt: "May 10, 2023",
  },
  {
    id: "job-9",
    title: "Marketing Specialist",
    location: "Remote",
    status: "Active",
    applications: 12,
    postedAt: "May 18, 2023",
  },
  {
    id: "job-10",
    title: "Customer Success Manager",
    location: "Chicago, IL",
    status: "Paused",
    applications: 8,
    postedAt: "May 5, 2023",
  },
  {
    id: "job-11",
    title: "QA Engineer",
    location: "San Francisco, CA",
    status: "Closed",
    applications: 15,
    postedAt: "April 20, 2023",
  },
]

